### PR TITLE
Add Laravel 5.3 support.

### PR DESCRIPTION
**Pull request by MichMich**

### CODE REVIEW

**Comment by skovmand** [comment]
Thanks!

**Comment by MichMich** [comment]
Could you please release a new release? (1.0.6) Otherwise, composer isn't satisfied with Laravel 5.3.

Thanks!

**Comment by skovmand** [comment]
Oh sorry. I forgot. Just did it.

**Comment by MichMich** [comment]
No problem. Works now. Thanks! :)

**Pull request merged**
