### PR TITLE
Allow for any version in the laravel 5.* series

### PR DESCRIPTION
**Pull request by mintbridge**

### CODE REVIEW

**Comment by skovmand** [comment]
Sounds reasonable. Have you tested it in 5.1?

**Comment by mintbridge** [comment]
Just doing that now, there aren't any api changes in 5.1 that would affect it so it should be fine

**Comment by mintbridge** [comment]
everything looks fine as far as i can tell

**Comment by skovmand** [comment]
Okay. I'll check it myself later as well....

However, in my opinion the versioning should allow for laravel 5.0.\* and 5.1.\* as we can't be sure something changes for 5.2. But it probably won't change for 5.2, since it is such basic implementation. But better safe than sorry, I think....

That would be in composer.json: 
"laravel/framework": "5.0-5.1"
(which becomes version >= 5.0 and version < 5.2 (see https://getcomposer.org/doc/01-basic-usage.md)

**Comment by mintbridge** [comment]
sounds like a safe and sensible plan

**Comment by skovmand** [comment]
But thanks for the PR!

I won't merge this one, but change it to one with "laravel/framework": "5.0-5.1" ... 
If you'd like to make a new PR with this you're welcome!

**Pull request closed without merging**
